<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../public/styles/compiled/style.css">
    <title>Калькулятор</title>
</head>
<body>
<form action="" class="calculator">
    <fieldset>
        <legend>Калькулятор</legend>
        <label for="first_number">Введите первое число</label>
        <input type="number" id="first_number" min="-10000" max="10000" name="first_number" required step="any">
        <br>
        <label for="operation">Выберите операцию</label>
        <select name="operation" id="operation">
            <option value="+" selected>Сложение</option>
            <option value="-">Вычитание</option>
            <option value="*">Умножение</option>
            <option value="/">Деление</option>
        </select>
        <br>
        <label for="second_number">Введите второе число</label>
        <input type="number" id="second_number" min="-10000" max="10000" name="second_number" required step="any">
        <br>
        <button type="reset">Очистить поля</button>
        <button>Отправить</button>
    </fieldset>
    <fieldset   >
        <legend>Результат</legend>
        <label for="answer">Ответ</label>
        <br>
        <input id="answer" readonly size="50" value="<?=calculation($first_number, $second_number, $operation)?>">
    </fieldset>
</form>

</body>
</html>