<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../public/styles/compiled/style.css">
    <title><?=$title?></title>
</head>
<body>
<h1><?=$title?></h1>
<?php foreach ($products as $product):?>
    <section class="product">
        <h2>Название: <?=$product['name'];?></h2>
        <p>Краткая характеристика: <?=$product['short_description'];?></p>
        <p>Цена: <?=$product['price'];?></p>
        <img src="<?=$product['thumb_path'];?>" alt="Image">
        <?php
        $get_params = '';
        foreach ($product as $item=>$value){
            $get_params .= $item . '=' . $value . '&';
        }
        ?>
        <a href="single_product.php?<?=rtrim($get_params, '&');?>">Подробнее</a>
    </section>
<?php endforeach;?>

</body>
</html>