<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Image</title>
    <link rel="stylesheet" href="../public/styles/compiled/style.css">
</head>
<body>
<header>

</header>

<aside>

</aside>

<main class="gallery">
    <img src="<?=$path;?>" alt="Image">

    <form action="" method="post" enctype="multipart/form-data" class="feedback" id="form">
        <label for="comment">Оставьте ваш комментарий</label>
        <textarea name="comment" id="comment" cols="30" rows="10" form="form"></textarea>
        <input type="submit" value="Отправить">
    </form>

    <div>
        <?php foreach ($comments as $comment):?>
            <p><?=$comment['comment']?></p>
        <?php endforeach;?>
    </div>

</main>



<footer>
    <span>
        Copyright &copy; Denis Lomakin
        <?= $current_year ?>
    </span>
</footer>

</body>
</html>